---
- name: Install a gnupg.
  apt:
    name: gnupg
    state: present

- name: Add an apt key.
  apt_key:
    id: php-sury
    url: 'https://packages.sury.org/php/apt.gpg'
    state: present

- name: Install packages.
  apt:
    name: '{{ php_packages }}'
    state: present