---
- name: 'SURY: Tasks for Debian'
  include_tasks: setup-Debian.yml
  when: ansible_facts['distribution'] == "Debian"

- name: 'SURY: Tasks for Ubuntu'
  include_tasks: setup-Ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"